services:
    Gpenverne\CloudflareBundle\Services\CloudflareService:
        public: true
        arguments: [""]

    cloudflare.service:
        alias: Gpenverne\CloudflareBundle\Services\CloudflareService
        public: true
        deprecated: ~
