services:
    Gpenverne\CloudflareBundle\Factory\CloudflareServiceFactory: ~

    cloudflare.service_factory:
        alias: Gpenverne\CloudflareBundle\Factory\CloudflareServiceFactory
        deprecated: ~

    Gpenverne\CloudflareBundle\Services\CloudflareService:
        factory: ['@cloudflare.service_factory', createCloudflareService]
        arguments:
            - "%cloudflare.api_email%"
            - "%cloudflare.api_key%"

    cloudflare.service:
        alias: Gpenverne\CloudflareBundle\Services\CloudflareService
        deprecated: ~
